"""rbac roles, api key scope, audit events

Revision ID: 0eeec470d827
Revises: 7190f0301d27
Create Date: 2026-08-13 12:36:42.905913
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0eeec470d827'
down_revision: Union[str, None] = '7190f0301d27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE memberrole ADD VALUE 'ADMIN'")
    op.execute("ALTER TYPE memberrole ADD VALUE 'VIEWER'")
    op.create_table('rbac_audit_events',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_api_key_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_api_key_id'], ['api_keys.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rbac_audit_user_created', 'rbac_audit_events', ['actor_user_id', 'created_at'], unique=False)
    op.create_index('idx_rbac_audit_workspace_created', 'rbac_audit_events', ['workspace_id', 'created_at'], unique=False)
    op.add_column('api_keys', sa.Column('workspace_id', sa.UUID(), nullable=True))
    sa.Enum('READ', 'WRITE', 'ADMIN', name='apikeyscope').create(op.get_bind(), checkfirst=True)
    op.add_column('api_keys', sa.Column('scope', sa.Enum('READ', 'WRITE', 'ADMIN', name='apikeyscope'), server_default=sa.text("'READ'"), nullable=False))
    op.create_index(op.f('ix_api_keys_workspace_id'), 'api_keys', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'api_keys', 'workspaces', ['workspace_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    op.drop_index(op.f('ix_api_keys_workspace_id'), table_name='api_keys')
    op.drop_column('api_keys', 'scope')
    op.drop_column('api_keys', 'workspace_id')
    op.drop_index('idx_rbac_audit_workspace_created', table_name='rbac_audit_events')
    op.drop_index('idx_rbac_audit_user_created', table_name='rbac_audit_events')
    op.drop_table('rbac_audit_events')

    # PostgreSQL cannot remove values from an enum type; memberrole keeps ADMIN/VIEWER.
    sa.Enum(name='apikeyscope').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
