"""upgrade_meeting_fields

Revision ID: 1d48b72162c4
Revises: 243dcb946edb
Create Date: 2026-06-24 18:30:21.758161
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1d48b72162c4'
down_revision: Union[str, None] = '243dcb946edb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('start_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('meetings', sa.Column('end_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'end_time')
    op.drop_column('meetings', 'start_time')
    # ### end Alembic commands ###
