"""add_cascade_delete_in_workspace

Revision ID: 243dcb946edb
Revises: 82e4af0e4e52
Create Date: 2026-06-24 17:42:09.002804
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '243dcb946edb'
down_revision: Union[str, None] = '82e4af0e4e52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_integration_user_id'), table_name='user_integrations')
    op.create_index(op.f('ix_user_integrations_user_id'), 'user_integrations', ['user_id'], unique=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('fk_workspaces_created_by'), 'workspaces', type_='foreignkey')
    op.create_foreign_key(None, 'workspaces', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspaces', type_='foreignkey')
    op.create_foreign_key(op.f('fk_workspaces_created_by'), 'workspaces', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_user_integrations_user_id'), table_name='user_integrations')
    op.create_index(op.f('idx_integration_user_id'), 'user_integrations', ['user_id'], unique=False)
    # ### end Alembic commands ###
