"""upgrade_meeting_with_google_meet

Revision ID: 3588929c7e60
Revises: 1d48b72162c4
Create Date: 2026-06-24 19:34:02.404352
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '3588929c7e60'
down_revision: Union[str, None] = '1d48b72162c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('google_calendar_event_id', sa.String(length=255), nullable=True))
    op.add_column('meetings', sa.Column('google_meet_url', sa.Text(), nullable=True))
    op.add_column('meetings', sa.Column('google_meet_code', sa.String(length=255), nullable=True))
    op.add_column('meetings', sa.Column('fireflies_meeting_id', sa.String(length=255), nullable=True))
    op.add_column('meetings', sa.Column('transcript_status', sa.String(length=50), nullable=True))
    op.add_column('meetings', sa.Column('guest_emails', postgresql.ARRAY(sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'guest_emails')
    op.drop_column('meetings', 'transcript_status')
    op.drop_column('meetings', 'fireflies_meeting_id')
    op.drop_column('meetings', 'google_meet_code')
    op.drop_column('meetings', 'google_meet_url')
    op.drop_column('meetings', 'google_calendar_event_id')
    # ### end Alembic commands ###
