"""P1-P3 indexes constraints notnull

Revision ID: 3c6687066a97
Revises: 854f803a7e40
Create Date: 2026-07-23 15:57:02.480200
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3c6687066a97'
down_revision: Union[str, None] = '854f803a7e40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_action_item_meeting_status', 'action_items', ['meeting_id', 'status'], unique=False)
    op.create_index('idx_action_item_project_status', 'action_items', ['project_id', 'status'], unique=False)
    op.alter_column('clients', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index('idx_decision_meeting_status', 'decisions', ['meeting_id', 'status'], unique=False)
    op.create_index('idx_decision_project_status', 'decisions', ['project_id', 'status'], unique=False)
    op.create_index('idx_suggestion_meeting_id', 'meeting_suggestions', ['meeting_id'], unique=False)
    op.create_index('idx_suggestion_status', 'meeting_suggestions', ['status'], unique=False)
    op.create_unique_constraint('uq_suggestion_meeting_title', 'meeting_suggestions', ['meeting_id', 'title'])
    op.alter_column('meetings', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index('idx_invitation_email_resource', 'member_invitations', ['email', 'resource_type', 'resource_id'], unique=False)
    op.create_unique_constraint('uq_invitation_email_resource_status', 'member_invitations', ['email', 'resource_type', 'resource_id', 'status'])
    op.alter_column('projects', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index('idx_question_meeting_status', 'questions', ['meeting_id', 'status'], unique=False)
    op.create_index('idx_question_project_status', 'questions', ['project_id', 'status'], unique=False)
    op.create_index('idx_requirement_meeting_status', 'requirements', ['meeting_id', 'status'], unique=False)
    op.create_index('idx_requirement_project_status', 'requirements', ['project_id', 'status'], unique=False)
    op.create_index(op.f('ix_requirements_priority'), 'requirements', ['priority'], unique=False)
    op.create_index('idx_risk_meeting_status', 'risks', ['meeting_id', 'status'], unique=False)
    op.create_index('idx_risk_project_status', 'risks', ['project_id', 'status'], unique=False)
    op.alter_column('workspaces', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspaces', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('idx_risk_project_status', table_name='risks')
    op.drop_index('idx_risk_meeting_status', table_name='risks')
    op.drop_index(op.f('ix_requirements_priority'), table_name='requirements')
    op.drop_index('idx_requirement_project_status', table_name='requirements')
    op.drop_index('idx_requirement_meeting_status', table_name='requirements')
    op.drop_index('idx_question_project_status', table_name='questions')
    op.drop_index('idx_question_meeting_status', table_name='questions')
    op.alter_column('projects', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('uq_invitation_email_resource_status', 'member_invitations', type_='unique')
    op.drop_index('idx_invitation_email_resource', table_name='member_invitations')
    op.alter_column('meetings', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('uq_suggestion_meeting_title', 'meeting_suggestions', type_='unique')
    op.drop_index('idx_suggestion_status', table_name='meeting_suggestions')
    op.drop_index('idx_suggestion_meeting_id', table_name='meeting_suggestions')
    op.drop_index('idx_decision_project_status', table_name='decisions')
    op.drop_index('idx_decision_meeting_status', table_name='decisions')
    op.alter_column('clients', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('idx_action_item_project_status', table_name='action_items')
    op.drop_index('idx_action_item_meeting_status', table_name='action_items')
    # ### end Alembic commands ###
