"""update db

Revision ID: 47a48b6163cf
Revises: ae3ef74d1a9c
Create Date: 2026-07-28 17:23:01.981003
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '47a48b6163cf'
down_revision: Union[str, None] = 'ae3ef74d1a9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create ENUM types before altering columns
    priority_enum = sa.Enum('low', 'medium', 'high', 'critical', name='priority')
    priority_enum.create(op.get_bind(), checkfirst=True)
    syncstatus_enum = sa.Enum('pending', 'synced', 'failed', 'conflict', name='syncstatus')
    syncstatus_enum.create(op.get_bind(), checkfirst=True)

    # Normalize existing priority data to match enum values before casting
    op.execute("UPDATE action_items SET priority = lower(priority) WHERE priority IS NOT NULL")
    op.execute("UPDATE action_items SET priority = NULL WHERE lower(priority) NOT IN ('low', 'medium', 'high', 'critical')")
    op.execute("UPDATE requirements SET priority = lower(priority) WHERE priority IS NOT NULL")
    op.execute("UPDATE requirements SET priority = NULL WHERE lower(priority) NOT IN ('low', 'medium', 'high', 'critical')")

    # Normalize existing sync_status data
    op.execute("UPDATE entity_integrations SET sync_status = lower(sync_status) WHERE sync_status IS NOT NULL")
    op.execute("UPDATE entity_integrations SET sync_status = NULL WHERE lower(sync_status) NOT IN ('pending', 'synced', 'failed', 'conflict')")

    op.add_column('action_items', sa.Column('assignee_id', sa.UUID(), nullable=True))
    op.add_column('action_items', sa.Column('assignee_name', sa.String(length=255), nullable=True))
    op.execute("ALTER TABLE action_items ALTER COLUMN priority TYPE priority USING priority::priority")
    op.drop_index(op.f('ix_action_items_assignee'), table_name='action_items')
    op.create_index(op.f('ix_action_items_assignee_id'), 'action_items', ['assignee_id'], unique=False)
    op.create_foreign_key(None, 'action_items', 'users', ['assignee_id'], ['id'], ondelete='SET NULL')
    op.drop_column('action_items', 'assignee')
    op.create_index('idx_api_keys_active', 'api_keys', ['user_id'], unique=False, postgresql_where=sa.text('revoked_at IS NULL'))
    op.execute("ALTER TABLE entity_integrations ALTER COLUMN sync_status TYPE syncstatus USING sync_status::syncstatus")
    op.create_index(op.f('ix_external_users_workspace_id'), 'external_users', ['workspace_id'], unique=False)
    op.drop_index(op.f('idx_chunk_meeting_id'), table_name='meeting_chunks')
    op.create_index('idx_suggestion_suggested_date', 'meeting_suggestions', ['suggested_date'], unique=False)
    op.drop_index(op.f('idx_invitation_email_resource'), table_name='member_invitations')
    op.create_index(op.f('ix_project_integrations_project_id'), 'project_integrations', ['project_id'], unique=False)
    op.execute("ALTER TABLE requirements ALTER COLUMN priority TYPE priority USING priority::priority")
    op.create_index(op.f('ix_workspace_integrations_workspace_id'), 'workspace_integrations', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspace_integrations_workspace_id'), table_name='workspace_integrations')
    op.execute("ALTER TABLE requirements ALTER COLUMN priority TYPE VARCHAR(50) USING priority::text")
    op.drop_index(op.f('ix_project_integrations_project_id'), table_name='project_integrations')
    op.create_index(op.f('idx_invitation_email_resource'), 'member_invitations', ['email', 'resource_type', 'resource_id'], unique=False)
    op.drop_index('idx_suggestion_suggested_date', table_name='meeting_suggestions')
    op.create_index(op.f('idx_chunk_meeting_id'), 'meeting_chunks', ['meeting_id'], unique=False)
    op.drop_index(op.f('ix_external_users_workspace_id'), table_name='external_users')
    op.execute("ALTER TABLE entity_integrations ALTER COLUMN sync_status TYPE VARCHAR(20) USING sync_status::text")
    op.drop_index('idx_api_keys_active', table_name='api_keys', postgresql_where=sa.text('revoked_at IS NULL'))
    op.add_column('action_items', sa.Column('assignee', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'action_items', type_='foreignkey')
    op.drop_index(op.f('ix_action_items_assignee_id'), table_name='action_items')
    op.create_index(op.f('ix_action_items_assignee'), 'action_items', ['assignee'], unique=False)
    op.execute("ALTER TABLE action_items ALTER COLUMN priority TYPE VARCHAR(50) USING priority::text")
    op.drop_column('action_items', 'assignee_name')
    op.drop_column('action_items', 'assignee_id')

    # Drop ENUM types
    sa.Enum(name='priority').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='syncstatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
