"""add membership constraints, remove redundant columns

Revision ID: 793aff4daee5
Revises: e1f2a3b4c5d6
Create Date: 2026-07-13 14:03:12.814729
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '793aff4daee5'
down_revision: Union[str, None] = 'e1f2a3b4c5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
        DELETE FROM client_members a
        USING client_members b
        WHERE a.id > b.id
          AND a.client_id = b.client_id
          AND a.user_id = b.user_id
    """)
    op.execute("""
        DELETE FROM project_members a
        USING project_members b
        WHERE a.id > b.id
          AND a.project_id = b.project_id
          AND a.user_id = b.user_id
    """)
    op.execute("""
        DELETE FROM workspace_members a
        USING workspace_members b
        WHERE a.id > b.id
          AND a.workspace_id = b.workspace_id
          AND a.user_id = b.user_id
    """)

    op.create_index(op.f('ix_client_members_client_id'), 'client_members', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_members_user_id'), 'client_members', ['user_id'], unique=False)
    op.create_unique_constraint('uq_client_member_user', 'client_members', ['client_id', 'user_id'])

    op.drop_column('meeting_analysis', 'generated_at')
    op.drop_constraint(op.f('meeting_suggestions_project_id_fkey'), 'meeting_suggestions', type_='foreignkey')
    op.drop_constraint(op.f('meeting_suggestions_client_id_fkey'), 'meeting_suggestions', type_='foreignkey')
    op.drop_column('meeting_suggestions', 'client_id')
    op.drop_column('meeting_suggestions', 'project_id')
    op.drop_column('project_jira', 'connected_at')

    op.create_index(op.f('ix_project_members_project_id'), 'project_members', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_members_user_id'), 'project_members', ['user_id'], unique=False)
    op.create_unique_constraint('uq_project_member_user', 'project_members', ['project_id', 'user_id'])

    op.create_index(op.f('ix_workspace_members_user_id'), 'workspace_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_members_workspace_id'), 'workspace_members', ['workspace_id'], unique=False)
    op.create_unique_constraint('uq_workspace_member_user', 'workspace_members', ['workspace_id', 'user_id'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_workspace_member_user', 'workspace_members', type_='unique')
    op.drop_index(op.f('ix_workspace_members_workspace_id'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_user_id'), table_name='workspace_members')
    op.drop_constraint('uq_project_member_user', 'project_members', type_='unique')
    op.drop_index(op.f('ix_project_members_user_id'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_project_id'), table_name='project_members')
    op.add_column('project_jira', sa.Column('connected_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('meeting_suggestions', sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('meeting_suggestions', sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('meeting_suggestions_client_id_fkey'), 'meeting_suggestions', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('meeting_suggestions_project_id_fkey'), 'meeting_suggestions', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.add_column('meeting_analysis', sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint('uq_client_member_user', 'client_members', type_='unique')
    op.drop_index(op.f('ix_client_members_user_id'), table_name='client_members')
    op.drop_index(op.f('ix_client_members_client_id'), table_name='client_members')
    # ### end Alembic commands ###
