"""refinements unique constraints nullable created_by

Revision ID: 7a98f4c2954c
Revises: 3c6687066a97
Create Date: 2026-07-23 16:04:44.269647
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7a98f4c2954c'
down_revision: Union[str, None] = '3c6687066a97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('uq_external_user'), 'external_users', type_='unique')
    op.create_unique_constraint('uq_external_user', 'external_users', ['workspace_id', 'provider', 'external_id'])
    op.drop_constraint(op.f('uq_suggestion_meeting_title'), 'meeting_suggestions', type_='unique')
    op.alter_column('meetings', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('uq_invitation_email_resource_status'), 'member_invitations', type_='unique')
    op.create_unique_constraint('uq_invitation_email_resource', 'member_invitations', ['email', 'resource_type', 'resource_id'])
    op.alter_column('projects', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('workspaces', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspaces', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('projects', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('uq_invitation_email_resource', 'member_invitations', type_='unique')
    op.create_unique_constraint(op.f('uq_invitation_email_resource_status'), 'member_invitations', ['email', 'resource_type', 'resource_id', 'status'], postgresql_nulls_not_distinct=False)
    op.alter_column('meetings', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_unique_constraint(op.f('uq_suggestion_meeting_title'), 'meeting_suggestions', ['meeting_id', 'title'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_external_user', 'external_users', type_='unique')
    op.create_unique_constraint(op.f('uq_external_user'), 'external_users', ['external_id', 'provider'], postgresql_nulls_not_distinct=False)
    op.alter_column('clients', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
