"""cascade to set null on created_by

Revision ID: ae3ef74d1a9c
Revises: 7a98f4c2954c
Create Date: 2026-07-28 16:05:22.980206
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ae3ef74d1a9c'
down_revision: Union[str, None] = '7a98f4c2954c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('clients_created_by_fkey'), 'clients', type_='foreignkey')
    op.create_foreign_key(None, 'clients', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('meetings_created_by_fkey'), 'meetings', type_='foreignkey')
    op.create_foreign_key(None, 'meetings', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('projects_created_by_fkey'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('workspaces_created_by_fkey'), 'workspaces', type_='foreignkey')
    op.create_foreign_key(None, 'workspaces', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspaces', type_='foreignkey')
    op.create_foreign_key(op.f('workspaces_created_by_fkey'), 'workspaces', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_created_by_fkey'), 'projects', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'meetings', type_='foreignkey')
    op.create_foreign_key(op.f('meetings_created_by_fkey'), 'meetings', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.create_foreign_key(op.f('clients_created_by_fkey'), 'clients', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
