"""add jira assignee columns

Revision ID: b79933cb8cc8
Revises: ef0cdedd747c
Create Date: 2026-07-16 16:49:30.442336
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b79933cb8cc8'
down_revision: Union[str, None] = 'ef0cdedd747c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action_items', sa.Column('jira_assignee_name', sa.String(length=255), nullable=True))
    op.add_column('action_items', sa.Column('jira_assignee_email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('action_items', 'jira_assignee_email')
    op.drop_column('action_items', 'jira_assignee_name')
    # ### end Alembic commands ###
