"""add jira_users and update action_items

Revision ID: bb2e30516371
Revises: b79933cb8cc8
Create Date: 2026-07-17 16:32:02.261550
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bb2e30516371'
down_revision: Union[str, None] = 'b79933cb8cc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jira_users',
    sa.Column('account_id', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('email_address', sa.String(length=255), nullable=True),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', name='uq_jira_users_account_id'),
    )
    op.create_index(op.f('ix_jira_users_account_id'), 'jira_users', ['account_id'], unique=True)
    op.create_index(op.f('ix_jira_users_workspace_id'), 'jira_users', ['workspace_id'], unique=False)
    op.add_column('action_items', sa.Column('jira_assignee_account_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_action_items_jira_assignee_account_id'), 'action_items', ['jira_assignee_account_id'], unique=False)
    op.create_foreign_key(None, 'action_items', 'jira_users', ['jira_assignee_account_id'], ['account_id'], ondelete='SET NULL')
    op.drop_column('action_items', 'jira_assignee_email')
    op.drop_column('action_items', 'jira_assignee_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action_items', sa.Column('jira_assignee_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('action_items', sa.Column('jira_assignee_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'action_items', type_='foreignkey')
    op.drop_index(op.f('ix_action_items_jira_assignee_account_id'), table_name='action_items')
    op.drop_column('action_items', 'jira_assignee_account_id')
    op.drop_index(op.f('ix_jira_users_workspace_id'), table_name='jira_users')
    op.drop_index(op.f('ix_jira_users_account_id'), table_name='jira_users')
    op.drop_constraint('uq_jira_users_account_id', 'jira_users', type_='unique')
    op.drop_table('jira_users')
    # ### end Alembic commands ###
