"""add_jira_sync

Revision ID: d320b931a506
Revises: 5936f8b0bbf5
Create Date: 2026-07-07 20:58:35.352453
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd320b931a506'
down_revision: Union[str, None] = '5936f8b0bbf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_member_jira_mappings',
    sa.Column('workspace_member_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('external_user_id', sa.String(length=255), nullable=False),
    sa.Column('external_display_name', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_member_id'], ['workspace_members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_member_id', 'provider', name='uq_member_jira_provider')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workspace_member_jira_mappings')
    # ### end Alembic commands ###
