"""drop_jira_sync_table_and_column

Revision ID: d57e30427ff8
Revises: 793aff4daee5
Create Date: 2026-07-14 15:12:15.043254
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd57e30427ff8'
down_revision: Union[str, None] = '793aff4daee5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workspace_member_jira_mappings')
    op.drop_column('member_invitations', 'sync_to_jira')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_invitations', sa.Column('sync_to_jira', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_table('workspace_member_jira_mappings',
    sa.Column('workspace_member_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('external_user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('external_display_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['workspace_member_id'], ['workspace_members.id'], name=op.f('workspace_member_jira_mappings_workspace_member_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('workspace_member_jira_mappings_pkey')),
    sa.UniqueConstraint('workspace_member_id', 'provider', name=op.f('uq_member_jira_provider'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
