"""add_normalized_meet_tables

Revision ID: d9aa226fe691
Revises: 3588929c7e60
Create Date: 2026-06-29 15:17:29.336119
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd9aa226fe691'
down_revision: Union[str, None] = '3588929c7e60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_items',
    sa.Column('assignee', sa.String(length=255), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('source_chunk_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['meeting_chunks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_action_item_meeting_id', 'action_items', ['meeting_id'], unique=False)
    op.create_index('idx_action_item_project_id', 'action_items', ['project_id'], unique=False)
    op.create_index('idx_action_item_status', 'action_items', ['status'], unique=False)
    op.create_index(op.f('ix_action_items_assignee'), 'action_items', ['assignee'], unique=False)
    op.create_index(op.f('ix_action_items_due_date'), 'action_items', ['due_date'], unique=False)
    op.create_index(op.f('ix_action_items_meeting_id'), 'action_items', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_action_items_project_id'), 'action_items', ['project_id'], unique=False)
    op.create_index(op.f('ix_action_items_status'), 'action_items', ['status'], unique=False)
    op.create_table('decisions',
    sa.Column('decision_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('source_chunk_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['meeting_chunks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_decision_meeting_id', 'decisions', ['meeting_id'], unique=False)
    op.create_index('idx_decision_project_id', 'decisions', ['project_id'], unique=False)
    op.create_index('idx_decision_status', 'decisions', ['status'], unique=False)
    op.create_index(op.f('ix_decisions_meeting_id'), 'decisions', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_decisions_project_id'), 'decisions', ['project_id'], unique=False)
    op.create_index(op.f('ix_decisions_status'), 'decisions', ['status'], unique=False)
    op.create_table('questions',
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('source_chunk_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['meeting_chunks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_question_meeting_id', 'questions', ['meeting_id'], unique=False)
    op.create_index('idx_question_project_id', 'questions', ['project_id'], unique=False)
    op.create_index('idx_question_status', 'questions', ['status'], unique=False)
    op.create_index(op.f('ix_questions_meeting_id'), 'questions', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_questions_project_id'), 'questions', ['project_id'], unique=False)
    op.create_index(op.f('ix_questions_status'), 'questions', ['status'], unique=False)
    op.create_table('requirements',
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('source_chunk_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['meeting_chunks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_requirement_meeting_id', 'requirements', ['meeting_id'], unique=False)
    op.create_index('idx_requirement_project_id', 'requirements', ['project_id'], unique=False)
    op.create_index('idx_requirement_status', 'requirements', ['status'], unique=False)
    op.create_index(op.f('ix_requirements_meeting_id'), 'requirements', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_requirements_project_id'), 'requirements', ['project_id'], unique=False)
    op.create_index(op.f('ix_requirements_status'), 'requirements', ['status'], unique=False)
    op.create_table('risks',
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('mitigation', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('source_chunk_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['meeting_chunks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_risk_meeting_id', 'risks', ['meeting_id'], unique=False)
    op.create_index('idx_risk_project_id', 'risks', ['project_id'], unique=False)
    op.create_index('idx_risk_status', 'risks', ['status'], unique=False)
    op.create_index(op.f('ix_risks_meeting_id'), 'risks', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_risks_project_id'), 'risks', ['project_id'], unique=False)
    op.create_index(op.f('ix_risks_severity'), 'risks', ['severity'], unique=False)
    op.create_index(op.f('ix_risks_status'), 'risks', ['status'], unique=False)
    op.drop_constraint(op.f('fk_clients_created_by'), 'clients', type_='foreignkey')
    op.create_foreign_key(None, 'clients', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_meetings_created_by'), 'meetings', type_='foreignkey')
    op.create_foreign_key(None, 'meetings', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_projects_created_by'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('fk_projects_created_by'), 'projects', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'meetings', type_='foreignkey')
    op.create_foreign_key(op.f('fk_meetings_created_by'), 'meetings', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.create_foreign_key(op.f('fk_clients_created_by'), 'clients', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_risks_status'), table_name='risks')
    op.drop_index(op.f('ix_risks_severity'), table_name='risks')
    op.drop_index(op.f('ix_risks_project_id'), table_name='risks')
    op.drop_index(op.f('ix_risks_meeting_id'), table_name='risks')
    op.drop_index('idx_risk_status', table_name='risks')
    op.drop_index('idx_risk_project_id', table_name='risks')
    op.drop_index('idx_risk_meeting_id', table_name='risks')
    op.drop_table('risks')
    op.drop_index(op.f('ix_requirements_status'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_project_id'), table_name='requirements')
    op.drop_index(op.f('ix_requirements_meeting_id'), table_name='requirements')
    op.drop_index('idx_requirement_status', table_name='requirements')
    op.drop_index('idx_requirement_project_id', table_name='requirements')
    op.drop_index('idx_requirement_meeting_id', table_name='requirements')
    op.drop_table('requirements')
    op.drop_index(op.f('ix_questions_status'), table_name='questions')
    op.drop_index(op.f('ix_questions_project_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_meeting_id'), table_name='questions')
    op.drop_index('idx_question_status', table_name='questions')
    op.drop_index('idx_question_project_id', table_name='questions')
    op.drop_index('idx_question_meeting_id', table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_decisions_status'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_project_id'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_meeting_id'), table_name='decisions')
    op.drop_index('idx_decision_status', table_name='decisions')
    op.drop_index('idx_decision_project_id', table_name='decisions')
    op.drop_index('idx_decision_meeting_id', table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_action_items_status'), table_name='action_items')
    op.drop_index(op.f('ix_action_items_project_id'), table_name='action_items')
    op.drop_index(op.f('ix_action_items_meeting_id'), table_name='action_items')
    op.drop_index(op.f('ix_action_items_due_date'), table_name='action_items')
    op.drop_index(op.f('ix_action_items_assignee'), table_name='action_items')
    op.drop_index('idx_action_item_status', table_name='action_items')
    op.drop_index('idx_action_item_project_id', table_name='action_items')
    op.drop_index('idx_action_item_meeting_id', table_name='action_items')
    op.drop_table('action_items')
    # ### end Alembic commands ###
